# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hzIS0VnthvnqnkvFI_XRY2tVVV4XUC1X

#### Exercises with `grep`
1.  How many uppercase words are there in the Avar Wikipedia? Lowercase?
    Hint: `wc -l` or `grep -c`
"""

sed 's/[^а-яА-ЯIӀ]\+/\n/g' < wiki.txt  | grep '^[а-яIӀ]' | wc -l

sed 's/[^а-яА-ЯIӀ]\+/\n/g' < wiki.txt | grep '^[А-ЯIӀ]' | wc -l

"""2.  How many 4-letter words?"""

sed 's/[^а-яА-ЯIӀ]\+/\n/g' < wiki.txt | grep -iP '^[А-ЯIӀ]{4}$' | wc -l

"""3.  Are there any words with no vowels?"""

sed 's/[^а-яА-ЯIӀ]\+/\n/g' < wiki.txt | grep -iP '^[^аэиоуяеыёю]*$' | wc -l

4.  Find \'\'1-syllable\'\' words (words with exactly one vowel)

sed 's/[^а-яА-ЯIӀ]\+/\n/g' < wiki.txt | grep -iP '^[^аэиоуяеыёю]*[аэиоуяеыёю][^аэиоуяеыёю]*$' | wc -l

"""5.  Find \'\'2-syllable\'\' words (words with exactly two vowels)"""

sed 's/[^а-яА-ЯIӀ]\+/\n/g' < wiki.txt | grep -iP '^[^аэиоуяеыёю]*[аэиоуяеыёю][^аэиоуяеыёю]*[аэиоуяеыёю][^аэиоуяеыёю]*$' | wc -l

"""### 7. `sed` (stream editor)

#### Exercises with `sed`

1. Count word initial consonant sequences: tokenise by word, delete the vowel and the rest of the word, and count
"""

sed 's/[^а-яА-ЯIӀ]\+/\n/g' < wiki.txt | sed -rn 's/(^[^аэиоуяеыёю]+).*/\1/Ip' | wc -l

"""2. Count word final consonant sequences"""

sed 's/[^а-яА-ЯIӀ]\+/\n/g' < wiki.txt | sed -rn 's/(.*[^аэиоуяеыёю]+)$/\1/Ip' | wc -l